name: EAS Android Build

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Expo/EAS cloud build (Android AAB)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas build --platform android --profile preview --non-interactive --wait

      - name: Download build artifact from Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          mkdir -p dist
          npx eas build:download --platform android --output-dir dist

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: dist/*.aab
